[package]
name = "labeler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0" }
serde_json = "1.0"

octocrab = "0.41"
ghactions = { version = "0.11", features = ["generate", "octocrab"] }

log = "0.4"
env_logger = "0.11"
